# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_new.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import random

import numpy
import time
from holoeye import slmdisplaysdk
from PyQt5 import QtCore, QtGui, QtWidgets
import numpy as np
from math import factorial
from scipy.special import assoc_laguerre as lg
import TimeTagger
from matplotlib.figure import Figure
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas

class MyMPLCanvas(FigureCanvas):
    def __init__(self):
        self.fig = Figure()
        self.ax = self.fig.add_subplot(111,autoscale_on=True)
        FigureCanvas.__init__(self, self.fig)
        # # we define the widget as expandable
        FigureCanvas.setSizePolicy(self,
                                   QtWidgets.QSizePolicy.Expanding,
                                   QtWidgets.QSizePolicy.Expanding)
        # notify the system of updated policy
        FigureCanvas.updateGeometry(self)

class Ui_forSLM(object):
    def setupUi(self, forSLM):
        forSLM.setObjectName("forSLM")
        forSLM.setEnabled(True)
        forSLM.resize(1880, 1050)
        forSLM.setAutoFillBackground(True)
        self.centralwidget = QtWidgets.QWidget(forSLM)
        self.centralwidget.setObjectName("centralwidget")
        self.Initialization = QtWidgets.QPushButton(self.centralwidget)
        self.Initialization.setGeometry(QtCore.QRect(10, 10, 141, 28))
        font = QtGui.QFont()
        font.setFamily("Bodoni MT")
        font.setPointSize(12)
        self.Initialization.setFont(font)
        self.Initialization.setObjectName("Initialization")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(670, 40, 201, 281))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.X_label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bodoni MT")
        font.setPointSize(12)
        self.X_label.setFont(font)
        self.X_label.setObjectName("X_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.X_label)
        self.X_index = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.X_index.setObjectName("X_index")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.X_index)
        self.Y_label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bodoni MT")
        font.setPointSize(12)
        self.Y_label.setFont(font)
        self.Y_label.setObjectName("Y_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Y_label)
        self.Y_index = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.Y_index.setObjectName("Y_index")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.Y_index)
        self.L_label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bodoni MT")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.L_label.setFont(font)
        self.L_label.setObjectName("L_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.L_label)
        self.L_index = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.L_index.setObjectName("L_index")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.L_index)
        self.P_label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bodoni MT")
        font.setPointSize(12)
        self.P_label.setFont(font)
        self.P_label.setObjectName("P_label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.P_label)
        self.P_index = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.P_index.setObjectName("P_index")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.P_index)
        self.Weight_label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bodoni MT")
        font.setPointSize(12)
        self.Weight_label.setFont(font)
        self.Weight_label.setObjectName("Weight_label")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.Weight_label)
        self.weight_index = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.weight_index.setObjectName("weight_index")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.weight_index)
        self.Waist_label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bodoni MT")
        font.setPointSize(12)
        self.Waist_label.setFont(font)
        self.Waist_label.setObjectName("Waist_label")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.Waist_label)
        self.waist_index = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.waist_index.setObjectName("waist_index")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.waist_index)
        self.Period_label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bodoni MT")
        font.setPointSize(12)
        self.Period_label.setFont(font)
        self.Period_label.setObjectName("Period_label")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.Period_label)
        self.Period_index = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.Period_index.setObjectName("Period_index")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.Period_index)
        self.Gray_levels_label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bodoni MT")
        font.setPointSize(12)
        self.Gray_levels_label.setFont(font)
        self.Gray_levels_label.setObjectName("Gray_levels_label")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.Gray_levels_label)
        self.Calc_LG = QtWidgets.QPushButton(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bodoni MT")
        font.setPointSize(11)
        self.Calc_LG.setFont(font)
        self.Calc_LG.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.Calc_LG.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.Calc_LG.setObjectName("Calc_LG")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.Calc_LG)
        self.GrayLevels_index = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.GrayLevels_index.setObjectName("GrayLevels_index")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.GrayLevels_index)
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(400, 440, 250, 189))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.Step_label = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Bodoni MT")
        font.setPointSize(12)
        self.Step_label.setFont(font)
        self.Step_label.setObjectName("Step_label")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.Step_label)
        self.Range_label = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Bodoni MT")
        font.setPointSize(12)
        self.Range_label.setFont(font)
        self.Range_label.setObjectName("Range_label")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.Range_label)
        self.start_scanning = QtWidgets.QPushButton(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Bodoni MT")
        font.setPointSize(12)
        self.start_scanning.setFont(font)
        self.start_scanning.setObjectName("start_scanning")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.start_scanning)
        self.accum_time_label = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Bodoni MT")
        font.setPointSize(12)
        self.accum_time_label.setFont(font)
        self.accum_time_label.setObjectName("accum_time_label")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.accum_time_label)
        self.Step_index = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.Step_index.setObjectName("Step_index")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.Step_index)
        self.Range_index = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.Range_index.setObjectName("Range_index")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.Range_index)
        self.Accum_time_index = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.Accum_time_index.setObjectName("Accum_time_index")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.Accum_time_index)
        self.Scanning_label = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Bodoni MT")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Scanning_label.setFont(font)
        self.Scanning_label.setObjectName("Scanning_label")
        self.Scanning_label.setWordWrap(True)
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.Scanning_label)
        self.Scanning_view_label = QtWidgets.QLabel(self.centralwidget)
        self.Scanning_view_label.setGeometry(QtCore.QRect(110, 430, 201, 27))
        font = QtGui.QFont()
        font.setFamily("Bodoni MT")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Scanning_view_label.setFont(font)
        self.Scanning_view_label.setObjectName("Scanning_view_label")
        self.Close_APP = QtWidgets.QPushButton(self.centralwidget)
        self.Close_APP.setGeometry(QtCore.QRect(520, 10, 141, 28))
        font = QtGui.QFont()
        font.setFamily("Bodoni MT")
        font.setPointSize(12)
        self.Close_APP.setFont(font)
        self.Close_APP.setObjectName("Close_APP")
        self.channel_1_index = QtWidgets.QSpinBox(self.centralwidget)
        self.channel_1_index.setMinimum(1)
        self.channel_1_index.setMaximum(8)
        self.channel_1_index.setGeometry(QtCore.QRect(1210, 10, 50, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.channel_1_index.setFont(font)
        self.channel_1_index.setObjectName("channel_1_index")
        self.channel_2_index = QtWidgets.QSpinBox(self.centralwidget)
        self.channel_2_index.setMinimum(1)
        self.channel_2_index.setMaximum(8)
        self.channel_2_index.setGeometry(QtCore.QRect(1720, 10, 50, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.channel_2_index.setFont(font)
        self.channel_2_index.setObjectName("channel_2_index")
        self.channel_1_label = QtWidgets.QLabel(self.centralwidget)
        self.channel_1_label.setGeometry(QtCore.QRect(1010, 20, 170, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.channel_1_label.setFont(font)
        self.channel_1_label.setObjectName("channel_1_label")
        self.channel_2_label = QtWidgets.QLabel(self.centralwidget)
        self.channel_2_label.setGeometry(QtCore.QRect(1500, 20, 160, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.channel_2_label.setFont(font)
        self.channel_2_label.setObjectName("channel_2_label")
        self.start_count_1 = QtWidgets.QPushButton(self.centralwidget)
        self.start_count_1.setGeometry(QtCore.QRect(970, 380, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.start_count_1.setFont(font)
        self.start_count_1.setObjectName("start_count_1")
        self.stop_count_1 = QtWidgets.QPushButton(self.centralwidget)
        self.stop_count_1.setGeometry(QtCore.QRect(1190, 380, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.stop_count_1.setFont(font)
        self.stop_count_1.setObjectName("stop_count_1")
        self.bin_width_1_index = QtWidgets.QLineEdit(self.centralwidget)
        self.bin_width_1_index.setGeometry(QtCore.QRect(1010, 340, 70, 30))
        self.bin_width_1_index.setObjectName("bin_width_1_index")
        self.bin_width_1_label = QtWidgets.QLabel(self.centralwidget)
        self.bin_width_1_label.setGeometry(QtCore.QRect(920, 340, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bin_width_1_label.setFont(font)
        self.bin_width_1_label.setObjectName("bin_width_1_label")
        self.bins_number_1_index = QtWidgets.QLineEdit(self.centralwidget)
        self.bins_number_1_index.setGeometry(QtCore.QRect(1280, 340, 70, 30))
        self.bins_number_1_index.setObjectName("bins_number_1_index")
        self.bins_number_1_label = QtWidgets.QLabel(self.centralwidget)
        self.bins_number_1_label.setGeometry(QtCore.QRect(1150, 340, 110, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bins_number_1_label.setFont(font)
        self.bins_number_1_label.setObjectName("bins_number_1_label")
        self.start_count_2 = QtWidgets.QPushButton(self.centralwidget)
        self.start_count_2.setGeometry(QtCore.QRect(1500, 380, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.start_count_2.setFont(font)
        self.start_count_2.setObjectName("start_count_2")
        self.stop_count_2 = QtWidgets.QPushButton(self.centralwidget)
        self.stop_count_2.setGeometry(QtCore.QRect(1700, 380, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.stop_count_2.setFont(font)
        self.stop_count_2.setObjectName("stop_count_2")
        self.bins_number_2_label = QtWidgets.QLabel(self.centralwidget)
        self.bins_number_2_label.setGeometry(QtCore.QRect(1660, 340, 110, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bins_number_2_label.setFont(font)
        self.bins_number_2_label.setObjectName("bins_number_2_label")
        self.bins_number_2_index = QtWidgets.QLineEdit(self.centralwidget)
        self.bins_number_2_index.setGeometry(QtCore.QRect(1790, 340, 70, 30))
        self.bins_number_2_index.setObjectName("bins_number_2_index")
        self.bin_width_2_index = QtWidgets.QLineEdit(self.centralwidget)
        self.bin_width_2_index.setGeometry(QtCore.QRect(1530, 340, 70, 30))
        self.bin_width_2_index.setObjectName("bin_width_2_index")
        self.bin_width_2_label = QtWidgets.QLabel(self.centralwidget)
        self.bin_width_2_label.setGeometry(QtCore.QRect(1440, 340, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bin_width_2_label.setFont(font)
        self.bin_width_2_label.setObjectName("bin_width_2_label")
        self.correlation_historgram_label = QtWidgets.QLabel(self.centralwidget)
        self.correlation_historgram_label.setGeometry(QtCore.QRect(1200, 410, 240, 30))
        font = QtGui.QFont()
        font.setFamily("Bodoni MT")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.correlation_historgram_label.setFont(font)
        self.correlation_historgram_label.setObjectName("correlation_historgram_label")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(1070, 940, 103, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(1430, 940, 103, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.bins_number_corr_label = QtWidgets.QLabel(self.centralwidget)
        self.bins_number_corr_label.setGeometry(QtCore.QRect(1190, 900, 120, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bins_number_corr_label.setFont(font)
        self.bins_number_corr_label.setObjectName("bins_number_corr_label")
        self.bins_number_corr_index = QtWidgets.QLineEdit(self.centralwidget)
        self.bins_number_corr_index.setGeometry(QtCore.QRect(1320, 900, 80, 30))
        self.bins_number_corr_index.setObjectName("bins_number_corr_index")
        self.bib_width_corr_index = QtWidgets.QLineEdit(self.centralwidget)
        self.bib_width_corr_index.setGeometry(QtCore.QRect(1050, 900, 80, 30))
        self.bib_width_corr_index.setObjectName("bib_width_corr_index")
        self.bib_width_corr_label = QtWidgets.QLabel(self.centralwidget)
        self.bib_width_corr_label.setGeometry(QtCore.QRect(960, 900, 90, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bib_width_corr_label.setFont(font)
        self.bib_width_corr_label.setObjectName("bib_width_corr_label")
        self.accum_time_corr_label = QtWidgets.QLabel(self.centralwidget)
        self.accum_time_corr_label.setGeometry(QtCore.QRect(1440, 900, 150, 30))
        font = QtGui.QFont()
        font.setFamily("Bodoni MT")
        font.setPointSize(14)
        self.accum_time_corr_label.setFont(font)
        self.accum_time_corr_label.setObjectName("accum_time_corr_label")
        self.accum_time_corr_index = QtWidgets.QLineEdit(self.centralwidget)
        self.accum_time_corr_index.setGeometry(QtCore.QRect(1580, 900, 80, 30))
        self.accum_time_corr_index.setObjectName("accum_time_corr_index")

        self.channel_1_view = QtWidgets.QFrame(self.centralwidget)
        self.ch_1_view = MyMPLCanvas()
        self.layout3 = QtWidgets.QVBoxLayout(self.channel_1_view)
        self.layout3.addWidget(self.ch_1_view)

        self.channel_1_view.setGeometry(QtCore.QRect(880, 40, 490, 300))
        self.channel_1_view.setAutoFillBackground(True)
        self.channel_1_view.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.channel_1_view.setFrameShadow(QtWidgets.QFrame.Raised)
        self.channel_1_view.setObjectName("channel_1_view")

        self.channel_2_view = QtWidgets.QFrame(self.centralwidget)
        self.ch_2_view = MyMPLCanvas()
        self.layout4 = QtWidgets.QVBoxLayout(self.channel_2_view)
        self.layout4.addWidget(self.ch_2_view)

        self.channel_2_view.setGeometry(QtCore.QRect(1390, 40, 490, 300))
        self.channel_2_view.setAutoFillBackground(True)
        self.channel_2_view.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.channel_2_view.setFrameShadow(QtWidgets.QFrame.Raised)
        self.channel_2_view.setObjectName("channel_2_view")

        self.Correlation_view = QtWidgets.QWidget(self.centralwidget)
        self.corr_view = MyMPLCanvas()
#        toolbar = NavigationToolbar(self.corr_view,QtWidgets.QMainWindow)
        self.layout5 = QtWidgets.QVBoxLayout(self.Correlation_view)
        self.layout5.addWidget(self.corr_view)

        self.Correlation_view.setGeometry(QtCore.QRect(880, 440, 880, 460))
        self.Correlation_view.setAutoFillBackground(True)
        self.Correlation_view.setObjectName("widget")

        self.graphicsView = QtWidgets.QFrame(self.centralwidget)
        self.graph_view = MyMPLCanvas()
        self.layout2 = QtWidgets.QVBoxLayout(self.graphicsView)
        self.layout2.addWidget(self.graph_view)

        self.graphicsView.setGeometry(QtCore.QRect(10, 40, 650, 395))
        self.graphicsView.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.graphicsView.setAutoFillBackground(True)
        self.graphicsView.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.graphicsView.setFrameShadow(QtWidgets.QFrame.Raised)
        self.graphicsView.setObjectName("graphicsView")
        self.Scanning_view = QtWidgets.QFrame(self.centralwidget)

        self.Scanning_view.setGeometry(QtCore.QRect(10, 460, 380, 330))
        self.scan_view = MyMPLCanvas()
        self.layout2 = QtWidgets.QVBoxLayout(self.Scanning_view)
        self.layout2.addWidget(self.scan_view)

        self.Scanning_view.setAutoFillBackground(True)
        self.Scanning_view.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Scanning_view.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Scanning_view.setObjectName("Scanning_view")
        forSLM.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(forSLM)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1880, 26))
        self.menubar.setObjectName("menubar")
        forSLM.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(forSLM)
        self.statusbar.setObjectName("statusbar")
        forSLM.setStatusBar(self.statusbar)

        self.retranslateUi(forSLM)
        QtCore.QMetaObject.connectSlotsByName(forSLM)

        self.bin_width_1_index.setText('100')
        self.bin_width_2_index.setText('100')
        self.bins_number_1_index.setText('50')
        self.bins_number_2_index.setText('50')
        self.L_index.setText('1')
        self.P_index.setText('0')
        self.waist_index.setText('100')
        self.GrayLevels_index.setText('0.95')
        self.X_index.setText('0')
        self.Y_index.setText('0')
        self.Step_index.setText('10')
        self.Range_index.setText('200')
        self.Period_index.setText('10')
        self.shift_x = 0
        self.shitf_y = 0
        self.tagger = 0
        self.blaz_period = 0
        self.Accum_time_index.setText('1')
        self.start_count_1.clicked.connect(lambda: self.Start_count_1_threat())
        self.start_count_2.clicked.connect(lambda: self.Start_count_2_threat())
        self.Calc_LG.clicked.connect(lambda: self.plot())
        self.Initialization.clicked.connect(lambda: self.initializ())
        self.start_scanning.clicked.connect(lambda: self.scanning())
        self.Close_APP.clicked.connect(lambda: self.close_all())
        self._plot_ref = None
        self._plot_ref2 = None


    def initializ(self):

        self.slm = slmdisplaysdk.SLMDisplay()
        self.slm.utilsSLMPreviewShow()
        self.ErrorCode = self.slm.ErrorCode
        self.ShowFlags = self.slm.ShowFlags
        self.WIDTH  = self.slm.width_px # HARDCODED
        self.HEIGHT = self.slm.height_px # HARDCODED
        self.tagger = TimeTagger.createTimeTagger()
        self.tagger.setTriggerLevel(channel=1, voltage=0.5)
        self.tagger.setTriggerLevel(channel=2, voltage=0.5)
        self.tagger.setInputDelay(1,83500)

        self.timer1 = QtCore.QTimer()
        self.timer1.timeout.connect(self.start_count_channel_1)
        self.stop_count_1.clicked.connect(self.timer1.stop)
        self.timer2 = QtCore.QTimer()
        self.timer2.timeout.connect(self.start_count_channel_2)
        self.stop_count_2.clicked.connect(self.timer2.stop)
        self.ydata1 = 0
        self.ydata2 = 0

    def retranslateUi(self, forSLM):
        _translate = QtCore.QCoreApplication.translate
        forSLM.setWindowTitle(_translate("forSLM", "forSLM"))
        self.Initialization.setText(_translate("forSLM", "Initialization"))
        self.X_label.setText(_translate("forSLM", "    X  "))
        self.Y_label.setText(_translate("forSLM", "    Y  "))
        self.L_label.setText(_translate("forSLM", "L mode"))
        self.P_label.setText(_translate("forSLM", "P mode"))
        self.Weight_label.setText(_translate("forSLM", "Weight"))
        self.Waist_label.setText(_translate("forSLM", "Waist w0"))
        self.Period_label.setText(_translate("forSLM", "Period"))
        self.Gray_levels_label.setText(_translate("forSLM", "Gray levels"))
        self.Calc_LG.setText(_translate("forSLM", "Calc"))
        self.Step_label.setText(_translate("forSLM", "Step"))
        self.Range_label.setText(_translate("forSLM", "Range"))
        self.start_scanning.setText(_translate("forSLM", "Start"))
        self.accum_time_label.setText(_translate("forSLM", "Accum. time"))
        self.Scanning_label.setText(_translate("forSLM", "   Scanning parameters"))
        self.Scanning_view_label.setText(_translate("forSLM", "   Scanning map"))
        self.Close_APP.setText(_translate("forSLM", "Close APP"))
        self.channel_1_label.setText(_translate("forSLM", "Choose a channel"))
        self.channel_2_label.setText(_translate("forSLM", "Choose a channel"))
        self.start_count_1.setText(_translate("forSLM", "Start"))
        self.stop_count_1.setText(_translate("forSLM", "Stop"))
        self.bin_width_1_label.setText(_translate("forSLM", "Bin width"))
        self.bins_number_1_label.setText(_translate("forSLM", "Bins number"))
        self.start_count_2.setText(_translate("forSLM", "Start"))
        self.stop_count_2.setText(_translate("forSLM", "Stop"))
        self.bins_number_2_label.setText(_translate("forSLM", "Bins number"))
        self.bin_width_2_label.setText(_translate("forSLM", "Bin width"))
        self.correlation_historgram_label.setText(_translate("forSLM", "Correlations histogram"))
        self.pushButton_5.setText(_translate("forSLM", "Start"))
        self.pushButton_6.setText(_translate("forSLM", "Stop"))
        self.bins_number_corr_label.setText(_translate("forSLM", "Bins number"))
        self.bib_width_corr_label.setText(_translate("forSLM", "Bin width"))
        self.accum_time_corr_label.setText(_translate("forSLM", "Accum. time"))
    @property

    def stop_1(self):
        self.timer1.stop()

    def Start_count_1_threat(self):
        self.xdata1 = np.linspace(0, int(self.bins_number_1_index.text())-1, int(self.bins_number_1_index.text()))
        self.ydata1 = np.linspace(0, int(self.bins_number_1_index.text())-1, int(self.bins_number_1_index.text()))*0
        self.counter_1=TimeTagger.Counter(tagger=self.tagger, channels=[(self.channel_1_index.value())], binwidth=int(self.bin_width_1_index.text())*int(1E9), n_values=1)
        self.timer1.setInterval(int(self.bin_width_1_index.text()))
        self.timer1.start()

    def stop_2(self):
        # self.stop_index_1=True
        self.timer2.stop()

    def Start_count_2_threat(self):
        self.xdata2 = np.linspace(0, int(self.bins_number_2_index.text()) - 1, int(self.bins_number_2_index.text()))
        self.ydata2 = np.linspace(0, int(self.bins_number_2_index.text()) - 1,
                                      int(self.bins_number_2_index.text())) * 0
        self.counter_2 = TimeTagger.Counter(tagger=self.tagger, channels=[(self.channel_2_index.value())],
                                                binwidth=int(self.bin_width_2_index.text()) * int(1E9), n_values=1)
        self.timer2.setInterval(int(self.bin_width_2_index.text()))
        self.timer2.start()

        #self.Thread_channnel_1 = Thread(self.start_count_channel_1())
        #self.Thread_channnel_1.start()
        #self.Thread_channnel_1.join()


    def start_count_channel_1(self):
        #while self.stop_index_1 != False:
        data1=self.counter_1.getData()
        #self.counter_1.waitUntilFinished()
        self.ydata1=self.ydata1[1:]
        self.ydata1=np.append(self.ydata1,data1)
        if self._plot_ref is None:
            plot_refs = self.ch_1_view.ax.plot(self.xdata1, self.ydata1, 'r')
            self._plot_ref = plot_refs[0]
        else:
            self._plot_ref.set_ydata(self.ydata1)
            self.ch_1_view.ax.relim()
            self.ch_1_view.ax.autoscale_view(True,True,True)
        self.ch_1_view.draw()

    def start_count_channel_2(self):
        #while self.stop_index_1 != False:
        data2=self.counter_2.getData()
        #self.counter_1.waitUntilFinished()
        self.ydata2=self.ydata2[1:]
        self.ydata2=np.append(self.ydata2,data2)
        if self._plot_ref2 is None:
            plot_refs = self.ch_2_view.ax.plot(self.xdata2, self.ydata2, 'r')
            self._plot_ref2 = plot_refs[0]
        else:
            self._plot_ref2.set_ydata(self.ydata2)
            self.ch_2_view.ax.relim()
            self.ch_2_view.ax.autoscale_view(True,True,True)
        self.ch_2_view.draw()
        #print('888')

    def LG_mode(self):

        x = -1 * np.linspace(-1 * self.WIDTH / 2, self.WIDTH / 2 - 1, self.WIDTH) + self.X + self.shift_x
        y = np.linspace(-1 * self.HEIGHT / 2, self.HEIGHT / 2 - 1, self.HEIGHT) + self.Y + self.shitf_y
        xv, yv = np.meshgrid(x, y)
        rho = np.hypot(xv, yv)
        phi = np.arctan2(yv, xv)
        i = 0
        l = (self.L_index.text()).split(' ')
        for i in range(l.__len__()):
            l[i] = int(l[i])
        p = int(self.P_index.text())
        w0 = int(self.waist_index.text())
        rho2w = rho / w0
        res = numpy.zeros((self.HEIGHT, self.WIDTH))
        for i in range(l.__len__()):
            res = res + np.sqrt(factorial(p) / factorial(p + np.absolute(l[i]))) * np.power(np.sqrt(2) * rho2w,
                                                                                            np.absolute(l[i])) * lg(
                2 * np.power(rho2w, 2), p, np.absolute(l[i])) * np.exp(-1 * np.power(rho2w, 2)) * np.exp(
                -1j * l[i] * phi)
        amp = np.absolute(res)
        phase = np.angle(res)
        amp = amp / np.amax(amp)
        phase = phase - np.pi * amp
        phase_mod = (phase + 2 * np.pi * xv / (self.blaz_period)) % (2 * np.pi) / (2 * np.pi)
        res = phase_mod * amp
        return (res) * float(self.GrayLevels_index.text())

    def scanning(self):
        step = int(self.Step_index.text())
        range = int(self.Range_index.text())
        self.corr_scan = TimeTagger.Correlation(self.tagger, 1, 2, 1000, 20)
        time.sleep(1)
        n = 0
        m = 0
        g = np.linspace(-1 * range / 2, range / 2, int(range / step) + 1)
        res1 = np.zeros((int(range / step) + 1, int(range / step) + 1))
        for i in g:
            self.shift_x = i
            for j in g:
                self.shitf_y = j
                data = (self.LG_mode())
                error = self.slm.showData(data)
                assert error == self.ErrorCode.NoError, self.slm.errorString(error)
                t = int(self.Accum_time_index.text()) * 1E12
                self.corr_scan.startFor(capture_duration=int(t))
                self.corr_scan.waitUntilFinished()
                res = (self.corr_scan.getData())
                res1[n][m] = res[9] - res[7]
                m = m + 1
            n = n + 1
            m = 0
            #
        self.shift_x = 0
        self.shitf_y = 0
        cp = self.scan_view.ax.contourf(g, g, res1, cmap='gray')
        cbar2 = self.scan_view.fig.colorbar(cp)
        self.scan_view.draw()
        cbar2.remove()

    def close_all(self):
        del self.tagger
        self.slm.release()
        self.slm.close()
        QtCore.QCoreApplication.quit()

    def plot(self):
        lg_data = slmdisplaysdk.createFieldSingle(self.slm.width_px, self.slm.height_px)
        self.X = int(self.X_index.text())
        self.Y = int(self.Y_index.text())
        self.blaz_period = int(self.Period_index.text())
        lg_data =(self.LG_mode())
        error = self.slm.showData(lg_data)
        cb = self.graph_view.ax.imshow(lg_data, cmap="gray")
        cbar = self.graph_view.fig.colorbar(cb, ax=self.graph_view.ax)
        self.graph_view.draw()
        assert error == self.ErrorCode.NoError, self.slm.errorString(error)
        cbar.remove()


if __name__ == '__main__':
     import sys

     app = QtWidgets.QApplication(sys.argv)
     MainWindow = QtWidgets.QMainWindow()
     ui = Ui_forSLM()
     ui.setupUi(MainWindow)
     MainWindow.show()
     sys.exit(app.exec_())
