BOX_IMAGE = "ubuntu/bionic64"
Vagrant.configure("2") do |config|
  config.vm.define "master" do |subconfig|
    subconfig.vm.box = BOX_IMAGE
	subconfig.vm.hostname = "master"
  config.vm.provision "shell", inline: <<-SHELL
	apt-get update && apt-get install -y avahi-daemon libnss-mdns
  SHELL
  subconfig.vm.network :private_network, ip: "169.254.136.243"

  end

  config.vm.define "node1" do |subconfig|
    subconfig.vm.box = BOX_IMAGE 
	subconfig.vm.hostname = "node1"
  config.vm.provision "shell", inline: <<-SHELL
	apt-get update && apt-get install -y avahi-daemon libnss-mdns
  SHELL
  subconfig.vm.network :private_network, ip: "169.254.136.244"

  end

  config.vm.define "node2" do |subconfig|
    subconfig.vm.box = BOX_IMAGE
	subconfig.vm.hostname = "node2"
  config.vm.provision "shell", inline: <<-SHELL
	apt-get update && apt-get install -y avahi-daemon libnss-mdns
  SHELL
  subconfig.vm.network :private_network, ip: "169.254.136.245"

  end

end
