BOX_IMAGE = "ubuntu/bionic64"
Vagrant.configure("2") do |config|
 config.vm.box = BOX_IMAGE
 config.vm.provision :shell, path: "bootstrap.sh"
 config.vm.network :forwarded_port, guest: 80, host: 4567
end
